language: python

env:
  global:
    - CIBW_BEFORE_BUILD='pip install numpy==1.10.0'

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2


install:
  - $PIP install cibuildwheel==0.9.4
  - git clone --depth=1 --recurse-submodules http://github.com/astropy/astropy-healpix

script:

  - cd astropy-healpix
  - cibuildwheel --output-dir wheelhouse
  - cd ..
