language: python

env:
  global:
    - CIBW_BEFORE_BUILD='pip install numpy==1.10.4 Cython'
    - CIBW_SKIP='cp33-* cp34-* cp37-*'

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2


install:
  - $PIP install cibuildwheel==0.9.4
  - git clone --recurse-submodules http://github.com/astropy/astropy-healpix

script:

  - cd astropy-healpix
  - git checkout v0.2.1
  - cibuildwheel --output-dir ../wheelhouse
  - cd ..

  - ls wheelhouse
