install:
  - pip install cibuildwheel==0.9.4 numpy==1.10.0
  - git clone http://github.com/astropy/astropy-healpix

build_script:
  - cd astropy-healpix
  - cibuildwheel --output-dir wheelhouse
  - cd ..

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
