environment:
  global:
    CIBW_BEFORE_BUILD: "pip install numpy==1.12.1"
    CIBW_SKIP: "cp33-* cp34-* cp37-*"

install:
  - pip install numpy==1.12.1
  - pip install git+https://github.com/astrofrog/autowheel.git

build_script:
  - mkdir wheelhouse
  - autowheel windows --output-dir=wheelhouse --ignore-existing
  - dir wheelhouse

artifacts:
  - path: "tests\\wheelhouse\\*.whl"
    name: Wheels
