environment:
  global:
    CIBW_BEFORE_BUILD: "pip install numpy==1.10.0"

install:
  - pip install cibuildwheel==0.9.4
  - git clone http://github.com/astropy/astropy-healpix

build_script:
  - cd astropy-healpix
  - cibuildwheel --output-dir wheelhouse
  - cd ..

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
