jobs:
- job: ${{ format(parameters.name) }}
  pool:
    ${{ if eq(parameters.os, 'windows') }}:
      vmImage: vs2017-win2016
    ${{ if eq(parameters.os, 'macos') }}:
      vmImage: macOS 10.13
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: Ubuntu 16.04

  steps:

  - script: pip install git+https://github.com/astrofrog/autowheel.git
    displayName: Installing autowheel

  - script: mkdir wheelhouse
    displayName: Making wheelhouse directory

  - script: autowheel ${{ parameters.os }} --output-dir=wheelhouse --ignore-existing
    displayName: Running autowheel
